#include <bits/stdc++.h>
using namespace std;
typedef long long int ll;

bool comp(ll a, ll b) 
{ 
    return (a < b); 
} 

int main() {
	int t;
	cin>>t;
	while(t--){
	    ll n1,n2,m;
	    cin>>n1>>n2>>m;
	    ll left;
	    ll x=(m*(m+1))/2;  ///Max number that can be generated by adding m distinct numbers
	    if(n1>=x&&n2>=x){
	        left=n1+n2-2*x;
	    }else{
	        if(n1>=n2){
	            left=n1-n2;
	        }else{
	            left=n2-n1;
	        }
	    }
	    cout<<left<<endl;
	}
	return 0;
}
